export const propertyCategories = [
  "Apartment/Flat",
  "Duplexes",
  "Detached Houses",
  "Semi-Detached Houses",
  "Bungalows",
  "Mansions",
  "Penthouses",
  "Condominiums",
  "Terraces/Townhouses",
  "Studio Apartments",
  "Mini Flats",
  "Self-Contain Rooms",
  "Office Spaces",
  "Shops/Retail Spaces",
  "Shopping Complexes",
  "Warehouses",
  "Hotels/Motels",
  "Restaurants/Bars",
  "Event Centers/Halls",
  "Co-working Spaces",
  "Fuel Stations",
  "Banks/Financial Buildings",
  "Industrial Properties",
  "Residential Land",
  "Commercial Land",
  "Agricultural Land",
  "Industrial Land",
  "Mixed-Use Land",
  "Estate Land",
  "Waterfront Land",
  "Dry Land",
  "Wet Land",
  "Luxury Apartments",
  "Smart Homes",
  "Beach Houses",
  "Golf Estate Villas",
  "Waterfront Mansions",
  "Serviced Apartments",
  "Private Estates",
  "Short-Term Luxury Rentals",
  "Airbnb-Style Shortlets",
  "Holiday Homes",
  "Guest Houses",
  "Lodges",
  "Vacation Homes",
  "Factories",
  "Industrial Warehouses",
  "Cold Rooms",
  "Power Plants",
  "Logistic Hubs",
  "Storage Facilities",
  "Farmland",
  "Poultry Farms",
  "Fish Farms",
  "Ranches",
  "Plantations",
  "Greenhouses",
  "Mixed-Use Buildings",
  "Estates for Sale",
  "Property Development Sites",
  "Joint Venture (JV) Properties",
  "Rental Income Properties",
  "Distressed/Foreclosure Properties",
  "Schools/Colleges",
  "Hospitals/Clinics",
  "Churches/Mosques",
  "Training Centers",
  "Government Buildings",
  "Newly Built",
  "Renovated",
  "Under Construction",
  "Off-Plan Projects",
  "Furnished Properties",
  "Serviced Properties",
  "Affordable Housing",
  "Smart/Automated Homes",
  "Gated Community Homes",
];
